In [1]:
import numpy as np

In [2]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
arr = np.random.rand(2,3)
arr

array([[0.28723183, 0.6272238 , 0.46474647],
       [0.92397755, 0.90428057, 0.95994271]])

In [6]:
arr = np.random.choice([0,1],size=(2,3))
arr

array([[1, 1, 1],
       [1, 1, 0]])

In [13]:
arr = np.random.rand(10,10)
arr

array([[0.74867709, 0.82538296, 0.51569578, 0.56357636, 0.66670407,
        0.24359777, 0.39690504, 0.36811884, 0.18713142, 0.12574342],
       [0.06661142, 0.7301997 , 0.9241327 , 0.20813147, 0.17584977,
        0.18445863, 0.44062817, 0.52391634, 0.99458317, 0.59921862],
       [0.34240984, 0.66427274, 0.14626091, 0.48023002, 0.98375883,
        0.52160241, 0.27501892, 0.27251439, 0.24778679, 0.28171586],
       [0.46157813, 0.47883258, 0.44388803, 0.34593225, 0.68818475,
        0.58499498, 0.07076991, 0.07635781, 0.2462626 , 0.31044038],
       [0.67690095, 0.27090231, 0.64689235, 0.75179698, 0.20823885,
        0.45460949, 0.83704438, 0.01655535, 0.50647186, 0.82665785],
       [0.60878325, 0.84082429, 0.40295044, 0.96699428, 0.75689646,
        0.2190066 , 0.7613371 , 0.48698119, 0.1902637 , 0.94241246],
       [0.42367359, 0.37308824, 0.87666622, 0.58393947, 0.16719895,
        0.23229588, 0.25260191, 0.94133818, 0.73124088, 0.8446736 ],
       [0.27987161, 0.92885801, 0.2512837

In [32]:
arr = np.random.randint(1,10, size=10)
arr

array([9, 9, 4, 4, 8, 5, 1, 6, 4, 5])

In [38]:
arr = np.array([[10,20,30],
               [40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
arr.shape # shows rows and columns

(2, 3)

In [35]:
arr.ndim # num of dimensions

2

In [36]:
arr.size # total num of elements

6

In [37]:
arr.dtype # data type 

dtype('int32')

In [39]:
arr = np.array([10,20,30,40,50,60,70,80,90])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
print(arr[1]) # index value

20


In [41]:
print(arr[1:5]) # slicing

[20 30 40 50]


In [43]:
arr = np.array([[10,20,30],
               [40,50,60],
               [70,80,90],
               [25,45,85],
               [45,78,25]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [25, 45, 85],
       [45, 78, 25]])

In [44]:
print(arr[:,1]) # column of 1 index

[20 50 80 45 78]


In [47]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
new_arr = arr.reshape(2,3) # convert into 2-d array
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr = np.array([[10,20],[30,40]])
arr

array([[10, 20],
       [30, 40]])

In [51]:
arr.flatten() # 2-d to 1-d

array([10, 20, 30, 40])

In [52]:
arr.ravel()

array([10, 20, 30, 40])