In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50]) # 1-d array
print(arr)

[10 20 30 40 50]


In [4]:
arr2=np.array([[10,20,30],
             [40,50,60]]) # 2-d array
print(arr2)

[[10 20 30]
 [40 50 60]]


In [5]:
arr = np.arange(10,30,2) # arange 
print(arr)

[10 12 14 16 18 20 22 24 26 28]


In [8]:
arr=np.linspace(0,100,5) # 5 spaces between 0 to 100 
print(arr)

[  0.  25.  50.  75. 100.]


In [9]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])